/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNI_ComReader */

#ifndef _Included_JNI_ComReader
#define _Included_JNI_ComReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_ComReader
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNI_ComReader_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
